spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/job_app
    username: root
    password: Goneanhem1

  main:
    allow-circular-references: true

  #    url: jdbc:mysql://localhost:3306/job_app
  #    username: root
  #    password: Hoang2002

  mail:
    host: smtp.gmail.com
    port: 587
    username: goneanhem@gmail.com
    password: test123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  openapi:
    url: http://localhost:8080
    description: Server URL in Development environment

jwt:
  access-token:
    expires: 864000000
  refresh-token:
    expires: 86400000